/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice.project;

import org.junit.jupiter.api.Test;

class ServerTest {
    @Test void appHasAGreeting() {
        CalculatorServer classUnderTest = new CalculatorServer();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
