/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice.project;
import io.javalin.Javalin;
import org.eclipse.jetty.util.thread.QueuedThreadPool;

/**
 * This is the server for the Diagram Composer Microservice.
 *
 * @author Traae
 * @version 0.1.0
 */
public class CalculatorServer {
    private static final int MAX_THREADS = 20;
    private static final int MIN_THREADS = 2;
    private static final int TIMEOUT = 60000;


    public static void main(String[] args) {
        String defaultMessage ="This is the Calculator Server";
        String apiInfo = "This api is for the Calculator Microservice. \n" +
                "We can return to you an output of up to 10 inputs. \n" +
                "COMMAND LIST:";

        Calculator calculator = Calculator.getInstance();


        QueuedThreadPool queuedThreadPool = new QueuedThreadPool(MAX_THREADS, MIN_THREADS,TIMEOUT);
        Javalin app = Javalin.create(config ->
                config.server(() ->
                        new CalculatorServer(queuedThreadPool)).start(7000);

        app.routes(() -> {
            // DUE TO MERGE ISSUES my work was deleted AGAIN.
            // It's fine, but ignore what is present below. I'll work it out as I do the composer.


            // Basic info calls
            app.get(, ctx -> ctx.result(defaultMessage));
            app.get(GeneralApi.getInfo.path(), ctx -> ctx.result(apiInfo));

            // Check status and Error message
            app.get(GeneralApi.getStatus.path(), ctx -> ctx.result("0"/* CALL FileExporter . get current status code ()*/));
            app.get(GeneralApi.getError.path(), ctx -> ctx.result("All good"/* CALL FileExporter . get error message ()*/));


            // Receive a diagram for rendering.
            app.post("/api/post/diagram", ctx -> {
                /*
                NOTE: I still do not full understand this conditional,
                specificly "application/json"

                if (Objects.equals(ctx.contentType(), "application/json")) {
                    // we make a diagram out of the diagram json that was sent to us.
                    Diagram d = ctx.bodyAsClass(Diagram.class);

                    ctx.result();
                }*/
            });
            app.get("/api/get/diagram", ctx -> {
                //ctx.json();
            });

        });

    }
}
